# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define :bare do |bare|
    bare.vm.hostname = "bare-01"
    bare.vm.network :public_network,
      dev: 'br0',
      mac: '080027FBADA1',
      auto_config: false
    bare.vm.provider :libvirt do |libvirt|
      libvirt.cpu_mode = 'host-passthrough'
      libvirt.memory = '12048'
      libvirt.cpus = '10'
      boot_network = {'dev' => 'br0'}
      libvirt.storage :file, :size => '80G'
      libvirt.boot boot_network
      #libvirt.boot 'hd'
      # VNC parameters
      libvirt.graphics_ip = '192.168.11.12'
      libvirt.video_type = 'qxl'
      # Set UEFI boot, comment for legacy
      libvirt.loader = '/usr/share/qemu/OVMF.fd'
      libvirt.nic_model_type = 'e1000'
    end
  end
end
