# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define :bare do |bare|
    bare.vm.hostname = "bare-01"
    bare.vm.network :public_network,
      dev: 'br0',
      mac: '808080AAEEDD',
      auto_config: false
    bare.vm.provider :libvirt do |libvirt|
      libvirt.cpu_mode = 'host-passthrough'
      libvirt.memory = '2048'
      libvirt.cpus = '1'
      boot_network = {'dev' => 'br0'}
      libvirt.storage :file, :size => '80G'
      libvirt.boot boot_network
      libvirt.boot 'hd'
      # Set UEFI boot, comment for legacy
      libvirt.loader = '/usr/share/qemu/OVMF.fd'
    end
  end
end
