# -*- mode: ruby -*-
# vi: set ft-ruby :

Vagrant.configure("2") do |config|
  config.vm.define "jnk" do |jnk|
    jnk.vm.box = "debian/bookworm64"
    jnk.vm.hostname = "jenkins"
    jnk.vm.network "public_network", ip: "192.168.31.96"
    jnk.vm.provision "shell", path: "provision.sh"

    jnk.vm.provider "virtualbox" do |v|
      v.memory = 2048
      v.cpus = 2
     end
  end

end
