# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

  # FOREMAN SERVER
  config.vm.define:foreman do |config|
    config.vm.box = "almalinux/8"
    config.vm.hostname = "foreman"
    config.vm.network "private_network", ip: "192.168.10.13"
    config.vm.provider "virtualbox" do |vb|
      vb.memory = 4096
      vb.cpus = 2
    end
  end

  # PXE MACHINE
  config.vm.define:pxe do |config|
    config.vm.box = "jtyr/pxe"
    config.vm.hostname = "pxe"
    config.vm.provider :virtualbox do |vb|
      # make sure this vm has enough memory to load the root fs into memory.
      vb.memory = 2048
      vb.gui = true

      # let vagrant known that the guest does not have the guest additions nor a functional vboxsf or shared folders.
      vb.check_guest_additions = false
      vb.functional_vboxsf = false
      config.vm.synced_folder '.', '/vagrant', disabled: true
      config.vm.network "private_network", type: "dhcp", name: "vboxnet1"
      # configure for PXE boot.
      vb.customize ['modifyvm', :id, '--boot1', 'net']
      vb.customize ['modifyvm', :id, '--boot2', 'disk']
      vb.customize ['modifyvm', :id, '--biospxedebug', 'on']
      vb.customize ['modifyvm', :id, '--cableconnected2', 'on']
      vb.customize ['modifyvm', :id, '--nicbootprio2', '1']
      vb.customize ['modifyvm', :id, "--nictype2", '82540EM'] # Must be an Intel card (as-of VB 5.1 we cannot Intel PXE boot from a virtio-net card).
      vb.customize ['modifyvm', :id, "--macaddress2", '080027fbad17']

      # set some BIOS settings that will help us identify this particular machine.
      #
      #   VirtualBox          | Linux
      #   --------------------+----------------------------------------------
      #   DmiSystemVendor     | /sys/devices/virtual/dmi/id/sys_vendor
      #   DmiSystemProduct    | /sys/devices/virtual/dmi/id/product_name
      #   DmiSystemVersion    | /sys/devices/virtual/dmi/id/product_version
      #   DmiSystemSerial     | /sys/devices/virtual/dmi/id/product_serial
      #   DmiSystemSKU        | dmidecode
      #   DmiSystemUuid       | /sys/devices/virtual/dmi/id/product_uuid
      #   DmiChassisVendor    | /sys/devices/virtual/dmi/id/chassis_vendor
      #   DmiChassisType      | /sys/devices/virtual/dmi/id/chassis_type
      #   DmiChassisVersion   | /sys/devices/virtual/dmi/id/chassis_version
      #   DmiChassisSerial    | /sys/devices/virtual/dmi/id/chassis_serial
      #   DmiChassisAssetTag  | /sys/devices/virtual/dmi/id/chassis_asset_tag
      #
      # See https://www.virtualbox.org/svn/vbox/trunk/src/VBox/Devices/PC/DevPcBios.cpp
      # See https://www.virtualbox.org/browser/vbox/trunk/src/VBox/Devices/PC/BIOS
      # See https://www.virtualbox.org/svn/vbox/trunk/src/VBox/Devices/PC/BIOS/bios.c
      #
      # NB the VirtualBox BIOS is based on Plex86/Boch/QEMU.
      # NB dump extradata with VBoxManage getextradata $(cat .vagrant/machines/debianlive/virtualbox/id)
      vb.customize ['setextradata', :id, 'VBoxInternal/Devices/pcbios/0/Config/DmiSystemVendor',    'your vendor name here']
      vb.customize ['setextradata', :id, 'VBoxInternal/Devices/pcbios/0/Config/DmiSystemProduct',   'your product name here']
      vb.customize ['setextradata', :id, 'VBoxInternal/Devices/pcbios/0/Config/DmiSystemVersion',   'your product version here']
      vb.customize ['setextradata', :id, 'VBoxInternal/Devices/pcbios/0/Config/DmiSystemSerial',    'your product serial number here']
      vb.customize ['setextradata', :id, 'VBoxInternal/Devices/pcbios/0/Config/DmiSystemSKU',       'your product SKU here']
      vb.customize ['setextradata', :id, 'VBoxInternal/Devices/pcbios/0/Config/DmiSystemUuid',      '00000000-0000-4000-8000-000000000001']
      vb.customize ['setextradata', :id, 'VBoxInternal/Devices/pcbios/0/Config/DmiChassisVendor',   'your chassis vendor name here']
      vb.customize ['setextradata', :id, 'VBoxInternal/Devices/pcbios/0/Config/DmiChassisType',     '1']
      vb.customize ['setextradata', :id, 'VBoxInternal/Devices/pcbios/0/Config/DmiChassisVersion',  'your chassis version here']
      vb.customize ['setextradata', :id, 'VBoxInternal/Devices/pcbios/0/Config/DmiChassisSerial',   'your chassis serial number here']
      vb.customize ['setextradata', :id, 'VBoxInternal/Devices/pcbios/0/Config/DmiChassisAssetTag', 'your chassis asset tag here']
    end
  end
end
