# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define "rancher" do |rnchr|
    rnchr.vm.box = "debian/bookworm64"
    rnchr.vm.hostname = "rancher"
    rnchr.vm.network "public_network", ip: "192.168.31.81"
    rnchr.vm.provision "shell", path: "provision.sh"

    #ip route add 192.168.11.0/24 via 192.168.31.1
    #ip route add 192.168.100.0/24 via 192.168.31.1
    #ip route add 192.168.101.0/24 via 192.168.31.1
    #ip route add 192.168.102.0/24 via 192.168.31.1
    #ip route add 192.168.103.0/24 via 192.168.31.1
    #ip route add 192.168.104.0/24 via 192.168.31.1
    #ip route add 192.168.105.0/24 via 192.168.31.1

    rnchr.vm.provider "virtualbox" do |r|
      r.memory = 8192
      r.cpus = 4
    end
  end
end

