# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "boxomatic/centos-stream-9"
#  config.vm.network "private_network", ip: "192.168.31.95"

   config.vm.provider "virtualbox" do |vb|
     vb.gui = true
   end

   config.vm.provision "shell", inline: <<-SHELL
     sudo yum groupinstall "Server with GUI"
     sudo systemctl set-default graphical
   SHELL

end
