## Configuration parameters
BOX_BASE = "bento/ubuntu-20.04"

Vagrant.configure("2") do |config|
    config.vm.box = BOX_BASE
    config.vm.network "private_network", ip: "192.168.33.30"
    config.vm.provider "virtualbox" do |v|
      v.memory = 4096
      v.cpus = 2
    end
  end
  