## Configuration parameters
BOX_BASE = "bento/ubuntu-20.04"

Vagrant.configure("2") do |config|

  config.vm.define "awx01" do |awx01|
    awx01.vm.provider "virtualbox" do |vb_awx01|
      vb_awx01.memory = 4096
      vb_awx01.cpus = 2
    end

    awx01.vm.box = BOX_BASE
    awx01.vm.hostname = "awx01"
    awx01.vm.network "private_network", ip: "192.168.31.31"
    awx01.vm.provision "shell", path: "provision-awx.sh"
  end
end
