# -*- mode: ruby -*-
# vi: set ft=ruby :


#1. Use "Graphical Install" option on first boot
#2. xfreerdp3 /v:192.168.31.12:5915
#3. echo 1 > /proc/sys/net/ipv4/ip_forward
#4. ssh -L 127.0.0.1:8443:192.168.56.100:443 taro@192.168.31.12




HARVESTER_NODES = 5;
#INTERFACE = 'br0';

Vagrant.configure("2") do |config|

  # Harvester HCI nodes
  (1..HARVESTER_NODES).each do |i|

    config.vm.define "hvstr0#{i}p" do |hv|
      hv.vm.box = "jtyr/pxe"
      hv.vm.hostname = "hvstr0#{i}p"
      hv.disksize.size = '250GB'
      #hv.vm.provision "shell", path: "provision.sh"
      #hv.vm.network "public_network", ip: "192.168.12.9#{i}"


      # First interface   enp0s3
      #  IGNORE

      # Second interface  enp0s8
      hv.vm.network "private_network", ip: "192.168.56.1#{i}"

      # Third interface   enp0s9
      hv.vm.network "private_network", ip: "192.168.56.12#{i}"

      # Fourth interface  enp0s10
      hv.vm.network "private_network", ip: "192.168.56.13#{i}"


  
      config.vm.provider "virtualbox" do |v|
        v.memory = 16384
        v.cpus = 6
        v.customize ["modifyvm", :id, "--nested-hw-virt", "on"]
        v.customize ["modifyvm", :id, "--boot1", "disk", "--boot2", "dvd"]
        #v.disk :disk, size: "100GB", name: "secondary_disk" # Add a new 20GB disk named "secondary_disk"
        v.customize ["storageattach", :id, "--storagectl", "IDE", "--port", "1", "--device", "1", "--type", "dvddrive", "--medium", "/home/taro/harvester-v1.5.0-amd64.iso"]
        v.customize ["modifyvm", :id, "--vrde", "on"]
        v.customize ["modifyvm", :id, "--vrde-port", "591#{i}"]
        v.customize ["modifyvm", :id, "--vrde-address", "0.0.0.0"]

      end
    end
  end
end

