# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define "zabbix" do |zbx|
    zbx.vm.box = "debian/bookworm64"
    zbx.vm.hostname = "zabbix"
    zbx.vm.network "public_network", ip: "192.168.31.94"
    zbx.vm.provision "shell", path: "provision.sh"
  end