# vi: set ft=ruby ts=2 :

require 'yaml'

VAGRANTFILE_API_VERSION = "2"

# ensure libvirt is the default provider in case the vagrant box config
# doesn't specify it
ENV['VAGRANT_DEFAULT_PROVIDER'] = "libvirt"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # continerd is taking more than 60 seconds to shutdown in SUSE platforms
  # so increase the timeout to 120 seconds
  config.vm.graceful_halt_timeout = 120

  config.vm.define :debian do |debian|
    debian.vm.box = 'debian/bookworm64'
    debian.vm.hostname = 'rancher'
    debian.vm.network 'private_network',
      ip: "192.168.0.11",
      libvirt__network_name: 'harvester',
      # don't enable DHCP as this node will have it's now DHCP server for iPXE
      # boot
      libvirt__dhcp_enabled: false

    # VLANs Interface
    debian.vm.network 'private_network', 
      ip: "192.168.50.30",
      libvirt__network_name: 'vlans',
      libvirt__dhcp_enabled: true

    # Storage Interface
    debian.vm.network 'private_network', 
      ip: "192.168.60.30",
      libvirt__network_name: 'storage',
      libvirt__dhcp_enabled: true  


    debian.vm.provider :libvirt do |libvirt|
      libvirt.cpu_mode = 'host-passthrough'
      libvirt.memory = '4096'
      libvirt.cpus = '2'
    end
    #debian.vm.provision "file", source: "./cluster.yaml", destination: "/home/vagrant/cluster.yaml"
    #debian.vm.provision "shell", path: "RANCHER.sh"
    ## Use ansible to install server
    #pxe_server.vm.provision :ansible do |ansible|
    #  ansible.playbook = 'ansible/setup_pxe_server.yml'
    #  ansible.extra_vars = {
    #    settings: @settings
    #  }
    #end
  end
end
