## Configuration parameters
BOX_BASE = "almalinux/9"


Vagrant.configure("2") do |config|

  config.vm.define "k3s" do |k3s|
    k3s.vm.provider "virtualbox" do |vb_k3s|
      vb_k3s.memory = 4096
      vb_k3s.cpus = 2
    end

    k3s.vm.box = BOX_BASE
    k3s.vm.hostname = "k3s"
    k3s.vm.network "private_network", ip: "192.168.33.41"
    k3s.vm.provision "shell", path: "provision-k3s.sh"
  end

end
